# Generated by Django 3.0.4 on 2020-03-11 10:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import schools.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='max_num_of_students',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School', validators=[schools.models.restrict_num_of_student]),
        ),
    ]
